development:
  adapter: mysql2
  encoding: utf8
  database: dust-3-tester
  username: root
  password: 
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: dust-3-tester
  username: 
  password: 
  host: ganon.imagemanagement.com
